"""balances table

Revision ID: 4e42b4f7c18d
Revises: 229aadc7605e
Create Date: 2018-04-16 17:26:48.530785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e42b4f7c18d'
down_revision = '229aadc7605e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance_btc', sa.Float(), nullable=True),
    sa.Column('balance_usd', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_balance_btc'), 'balance', ['balance_btc'], unique=True)
    op.create_index(op.f('ix_balance_balance_usd'), 'balance', ['balance_usd'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_balance_usd'), table_name='balance')
    op.drop_index(op.f('ix_balance_balance_btc'), table_name='balance')
    op.drop_table('balance')
    # ### end Alembic commands ###
