"""empty message

Revision ID: 05fb72f5d4a2
Revises: ef6c0f6c770b
Create Date: 2018-05-01 10:29:49.458513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fb72f5d4a2'
down_revision = 'ef6c0f6c770b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_tx_id', table_name='transfer')
    op.create_index(op.f('ix_transfer_tx_id'), 'transfer', ['tx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_tx_id'), table_name='transfer')
    op.create_index('ix_transfer_tx_id', 'transfer', ['tx_id'], unique=1)
    # ### end Alembic commands ###
