"""empty message

Revision ID: 10f59e95a02f
Revises: 4e42b4f7c18d
Create Date: 2018-04-23 11:59:46.230375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f59e95a02f'
down_revision = '4e42b4f7c18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_balance_balance_btc', table_name='balance')
    op.create_index(op.f('ix_balance_balance_btc'), 'balance', ['balance_btc'], unique=False)
    op.drop_index('ix_balance_balance_usd', table_name='balance')
    op.create_index(op.f('ix_balance_balance_usd'), 'balance', ['balance_usd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_balance_usd'), table_name='balance')
    op.create_index('ix_balance_balance_usd', 'balance', ['balance_usd'], unique=1)
    op.drop_index(op.f('ix_balance_balance_btc'), table_name='balance')
    op.create_index('ix_balance_balance_btc', 'balance', ['balance_btc'], unique=1)
    # ### end Alembic commands ###
