"""empty message

Revision ID: 2a093b058f48
Revises: 97a714ef4486
Create Date: 2018-04-23 19:55:14.159804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a093b058f48'
down_revision = '97a714ef4486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('tx_type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_amount'), 'transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_transaction_currency'), 'transaction', ['currency'], unique=False)
    op.create_index(op.f('ix_transaction_price'), 'transaction', ['price'], unique=False)
    op.create_index(op.f('ix_transaction_timestamp'), 'transaction', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transaction_tx_id'), 'transaction', ['tx_id'], unique=True)
    op.create_index(op.f('ix_transaction_tx_type'), 'transaction', ['tx_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_tx_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_tx_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_timestamp'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_price'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_currency'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_amount'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
