"""empty message

Revision ID: 97a714ef4486
Revises: 10f59e95a02f
Create Date: 2018-04-23 14:11:05.860251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a714ef4486'
down_revision = '10f59e95a02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_first_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.drop_index('ix_user_last_name', table_name='user')
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=1)
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    # ### end Alembic commands ###
