"""empty message

Revision ID: ef6c0f6c770b
Revises: 2a093b058f48
Create Date: 2018-04-27 19:30:02.894242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6c0f6c770b'
down_revision = '2a093b058f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tx_type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_amount'), 'trade', ['amount'], unique=False)
    op.create_index(op.f('ix_trade_price'), 'trade', ['price'], unique=False)
    op.create_index(op.f('ix_trade_timestamp'), 'trade', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trade_total'), 'trade', ['total'], unique=False)
    op.create_index(op.f('ix_trade_tx_type'), 'trade', ['tx_type'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tx_type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_amount'), 'transfer', ['amount'], unique=False)
    op.create_index(op.f('ix_transfer_currency'), 'transfer', ['currency'], unique=False)
    op.create_index(op.f('ix_transfer_timestamp'), 'transfer', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transfer_tx_id'), 'transfer', ['tx_id'], unique=True)
    op.create_index(op.f('ix_transfer_tx_type'), 'transfer', ['tx_type'], unique=False)
    op.drop_index('ix_transaction_amount', table_name='transaction')
    op.drop_index('ix_transaction_currency', table_name='transaction')
    op.drop_index('ix_transaction_price', table_name='transaction')
    op.drop_index('ix_transaction_timestamp', table_name='transaction')
    op.drop_index('ix_transaction_tx_id', table_name='transaction')
    op.drop_index('ix_transaction_tx_type', table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tx_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('tx_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_tx_type', 'transaction', ['tx_type'], unique=False)
    op.create_index('ix_transaction_tx_id', 'transaction', ['tx_id'], unique=1)
    op.create_index('ix_transaction_timestamp', 'transaction', ['timestamp'], unique=False)
    op.create_index('ix_transaction_price', 'transaction', ['price'], unique=False)
    op.create_index('ix_transaction_currency', 'transaction', ['currency'], unique=False)
    op.create_index('ix_transaction_amount', 'transaction', ['amount'], unique=False)
    op.drop_index(op.f('ix_transfer_tx_type'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_tx_id'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_timestamp'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_currency'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_amount'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_trade_tx_type'), table_name='trade')
    op.drop_index(op.f('ix_trade_total'), table_name='trade')
    op.drop_index(op.f('ix_trade_timestamp'), table_name='trade')
    op.drop_index(op.f('ix_trade_price'), table_name='trade')
    op.drop_index(op.f('ix_trade_amount'), table_name='trade')
    op.drop_table('trade')
    # ### end Alembic commands ###
